name: Docker Preview Deployment

on:
  pull_request:
    branches: [main, master]
    types: [opened, synchronize, reopened]
    paths:
      - 'Dockerfile'
      - '.dockerignore'
      - 'package.json'
      - 'bun.lockb'
      - 'src/**'
      - 'static/**'

jobs:
  preview:
    name: Build and Deploy Preview
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get short SHA
        id: sha
        run: echo "short_sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get PR number
        id: pr
        run: echo "number=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/preview:pr-${{ steps.pr.outputs.number }}
            ghcr.io/${{ github.repository }}/preview:sha-${{ steps.sha.outputs.short_sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Comment on PR
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const repoName = '${{ github.repository }}';
            const prNumber = '${{ steps.pr.outputs.number }}';
            const shortSha = '${{ steps.sha.outputs.short_sha }}';

            const dockerPullCmd = `docker pull ghcr.io/${repoName}/preview:pr-${prNumber}`;
            const dockerRunCmd = `docker run -p 3000:3000 ghcr.io/${repoName}/preview:pr-${prNumber}`;

            const message = `## 🐳 Docker Preview Available

            A preview Docker image has been built for this pull request:

            \`\`\`bash
            # Pull the image
            ${dockerPullCmd}

            # Run the image (adjust ports as needed)
            ${dockerRunCmd}
            \`\`\`

            This image is also tagged with the commit SHA: \`ghcr.io/${repoName}/preview:sha-${shortSha}\`

            The preview image will be available for the duration of this pull request.`;

            github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: message
            });
